apiVersion: v1
kind: ServiceAccount
metadata:
  name: imds-webhook
  namespace: kubevirt-imds
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imds-webhook
rules:
# Needed to read pods for mutation
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Needed to read secrets for TLS (if using cert-manager)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imds-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: imds-webhook
subjects:
- kind: ServiceAccount
  name: imds-webhook
  namespace: kubevirt-imds
