apiVersion: v1
kind: Service
metadata:
  name: imds-webhook
  namespace: kubevirt-imds
  labels:
    app.kubernetes.io/name: imds-webhook
spec:
  selector:
    app.kubernetes.io/name: imds-webhook
  ports:
  - port: 443
    targetPort: 8443
    name: https
